// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmyFi2ERfZd4JHLxudw3cV0ELmjXBsxI0',
    appId: '1:967479662246:web:109927f1c48bcb81ac0667',
    messagingSenderId: '967479662246',
    projectId: 'hibye-chat-a5c8a',
    authDomain: 'hibye-chat-a5c8a.firebaseapp.com',
    storageBucket: 'hibye-chat-a5c8a.appspot.com',
    measurementId: 'G-9PTYN1JRWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLRXaNlwYwZLk3vz40Nrar1edff3Loruc',
    appId: '1:967479662246:android:3259c0da112d1ee4ac0667',
    messagingSenderId: '967479662246',
    projectId: 'hibye-chat-a5c8a',
    storageBucket: 'hibye-chat-a5c8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjWh3VyGmWLvqqWAJdduvZc8-uAt6N8Y',
    appId: '1:967479662246:ios:63699957e0d30eceac0667',
    messagingSenderId: '967479662246',
    projectId: 'hibye-chat-a5c8a',
    storageBucket: 'hibye-chat-a5c8a.appspot.com',
    iosClientId: '967479662246-f0igagiu0pn3njcbe6f8ugce83378l2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hibye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmjWh3VyGmWLvqqWAJdduvZc8-uAt6N8Y',
    appId: '1:967479662246:ios:63699957e0d30eceac0667',
    messagingSenderId: '967479662246',
    projectId: 'hibye-chat-a5c8a',
    storageBucket: 'hibye-chat-a5c8a.appspot.com',
    iosClientId: '967479662246-f0igagiu0pn3njcbe6f8ugce83378l2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hibye',
  );
}
